DB_NAME = "jewels"
DB_USER = "myuser"
DB_PASS = "mypass"
ADMIN_PASS = "mypass"
HTTP_DIR = "/var/www/jewels/"
SERVER_PORT = "8080"
EMAIL = "hey@test.com"
EMAIL_PASS = "pass"
SMTP = "mail.ex.com"
SMTP_PORT = "123"
ADMIN_EMAILS = ["test@test.com", "test@test.com"]